[project]
name = "Enalyzer"
version = "0.0.1"
authors = [
    {name="Josef M. Gallmetzer", email="gallmetzer.josef@gmail.com"},
    {name="Leo Christanell", email="leochristanell@gmail.com"}
]
description = "A package that help analyze PIMD-QMCF trajectories."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]