name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    
    - name: Set dummy display
      run: |
        export DISPLAY=:0
        echo "DISPLAY set to $DISPLAY"

    - name: build PQEnalyzer
      run: |
        pip install .[test]

    - name: Generate coverage report
      run: |
        export DISPLAY=:0
        echo "DISPLAY set to $DISPLAY"
        pip install pytest
        pip install pytest-cov
        python -m pytest --cov=PQEnalyzer --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        flags: unittests
        verbose: true
